development:
  adapter: postgresql
  encoding: unicode
  database: mileage_tracker
  pool: 2
  username: Michael Bade
  password: 1234bounce
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>